# Generated by Django 6.1.1 on 2026-09-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.CharField(help_text='Identificador único de la sesión de recomendación', max_length=100, verbose_name='ID de Sesión')),
                ('usuario', models.CharField(blank=True, default='Anónimo', max_length=150, verbose_name='Usuario (nombre o email)')),
                ('util', models.BooleanField(verbose_name='¿Fue útil esta recomendación?')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario adicional')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de valoración')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='equipos.equipo', verbose_name='Equipo valorado')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
