# Generated by Django 6.1.1 on 2026-09-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('laptop', 'Laptop'), ('pc_escritorio', 'PC de Escritorio')], default='laptop', max_length=20, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('procesador', models.CharField(max_length=200, verbose_name='Procesador')),
                ('memoria_ram', models.IntegerField(verbose_name='Memoria RAM (GB)')),
                ('almacenamiento', models.CharField(help_text='Ej: 512GB SSD, 1TB HDD', max_length=100, verbose_name='Almacenamiento')),
                ('tarjeta_grafica', models.CharField(blank=True, default='Integrada', max_length=200, verbose_name='Tarjeta Gráfica')),
                ('tamanio_pantalla', models.FloatField(blank=True, help_text='Opcional para PCs de escritorio', null=True, verbose_name='Tamaño de Pantalla (pulgadas)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (COP)')),
                ('tienda', models.CharField(max_length=150, verbose_name='Tienda')),
                ('enlace_compra', models.URLField(max_length=500, verbose_name='Enlace de Compra')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['precio'],
                'unique_together': {('marca', 'modelo', 'tienda')},
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio registrado (COP)')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha'],
            },
        ),
    ]
