# Generated by Django 6.1.1 on 2026-09-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Imagen / Thumbnail'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='enlace_compra',
            field=models.URLField(max_length=1000, verbose_name='Enlace de Compra'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (S/.)'),
        ),
    ]
